steps:
  # 1. Frontend Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wayn-ai-repo/wayn-ai-frontend:$COMMIT_SHA', './frontend']
    id: 'build-frontend'

  # 2. Frontend Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wayn-ai-repo/wayn-ai-frontend:$COMMIT_SHA']
    id: 'push-frontend'

  # 3. Frontend Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wayn-ai-frontend'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wayn-ai-repo/wayn-ai-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3' # Seoul region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--no-cpu-throttling'
      - '--min-instances'
      - '1' # 콜드 스타트 방지
    id: 'deploy-frontend'

  # 4. Backend Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wayn-ai-repo/wayn-ai-backend:$COMMIT_SHA', './backend']
    id: 'build-backend'

  # 5. Backend Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wayn-ai-repo/wayn-ai-backend:$COMMIT_SHA']
    id: 'push-backend'

  # 6. Backend Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wayn-ai-backend'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wayn-ai-repo/wayn-ai-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5001' # 백엔드 타겟 포트 설정
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-northeast3:wayn-ai'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://postgres:%21zxasqw12%40@localhost/WAYN-Ai-db?host=/cloudsql/$PROJECT_ID:asia-northeast3:wayn-ai'
      - '--no-cpu-throttling'
      - '--min-instances'
      - '1' # 콜드 스타트 방지
    id: 'deploy-backend'



images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wayn-ai-repo/wayn-ai-frontend:$COMMIT_SHA'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wayn-ai-repo/wayn-ai-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
